service: kizapp # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-2
  environment:
    GOOGLE_APPLICATION_CREDENTIALS: ${env:GOOGLE_APPLICATION_CREDENTIALS}
    NAVER_CLIENT_ID: ${env:NAVER_CLIENT_ID}
    NAVER_CLIENT_SECRET: ${env:NAVER_CLIENT_SECRET}

functions:
  translateToKorean:
    handler: handler.translateToKorean
    events:
      - http:
          path: translate
          method: post
          cors: true
